# Generated by Django 4.0 on 2022-02-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='task_body',
            field=models.TextField(default='body', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
