# Generated by Django 4.0 on 2022-03-04 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todolist_options_alter_todolist_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date_completed',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='todolist',
            name='date_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
