# Generated by Django 4.0 on 2022-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_todolist_date_completed_todolist_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_completed',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date_created',
            field=models.DateField(),
        ),
    ]
