# Generated by Django 4.0 on 2022-03-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_todolist_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_completed',
            field=models.DateField(null=True),
        ),
    ]
