# Generated by Django 4.0 on 2022-03-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_todolist_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='days_left',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
