# Generated by Django 4.0 on 2022-03-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_alter_todolist_days_left_todolist_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
