# Generated by Django 4.0 on 2022-03-18 23:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_todolist_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 23, 2, 40, 221605, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
