# Generated by Django 4.0 on 2022-03-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_todolist_date_end_alter_todolist_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
