# Generated by Django 4.0 on 2022-03-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_todolist_date_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='days_left',
        ),
    ]
